export const  user = [
  {
    _id: '6442cf3d65243e4434a28aa3',
    index: 0,
    guid: '58c639cc-debd-4978-8dcd-dbf0f81c4cd9',
    isActive: true,
    balance: '$2,949.45',
    picture: 'http://placehold.it/32x32',
    age: 25,
    eyeColor: 'green',
    name: 'Janna Bond',
    gender: 'female',
    company: 'CUIZINE',
    email: 'jannabond@cuizine.com',
    phone: '+1 (971) 475-3559',
    address: '534 Myrtle Avenue, Healy, Illinois, 6397',
    about:
      'Ullamco dolor cillum Lorem sunt occaecat. Eu commodo voluptate culpa magna nisi fugiat sunt ea amet. Est cillum commodo proident veniam adipisicing veniam eiusmod tempor.\r\n',
    registered: '2015-10-04T08:34:24 -03:00',
    latitude: -3.521427,
    longitude: -23.181361,
    tags: ['anim', 'ad', 'eu', 'labore', 'id', 'nulla', 'irure'],
    friends: [
      {
        id: 0,
        name: 'Jacquelyn Quinn',
      },
      {
        id: 1,
        name: 'Kimberly Ellis',
      },
      {
        id: 2,
        name: 'Robbie Maynard',
      },
    ],
    greeting: 'Hello, Janna Bond! You have 4 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '6442cf3d69e2215d8fe6ba0f',
    index: 1,
    guid: '457a1c9e-3095-4fe5-a9a4-81fb39d7d76b',
    isActive: false,
    balance: '$1,024.75',
    picture: 'http://placehold.it/32x32',
    age: 28,
    eyeColor: 'brown',
    name: 'Lucia Mathis',
    gender: 'female',
    company: 'VENDBLEND',
    email: 'luciamathis@vendblend.com',
    phone: '+1 (971) 558-3296',
    address: '468 Howard Alley, Thermal, Puerto Rico, 788',
    about:
      'Sint ipsum ea do est nulla. Officia id magna id dolor sit aliquip amet do nulla in occaecat. Officia occaecat anim do laboris anim enim et tempor elit eu sunt sunt non culpa. Proident sint ea nisi exercitation elit voluptate aliquip sint ad. Ullamco dolor est culpa labore excepteur ut id nulla est exercitation excepteur culpa labore deserunt.\r\n',
    registered: '2021-01-31T06:27:04 -03:00',
    latitude: -6.097101,
    longitude: -58.637687,
    tags: ['ea', 'elit', 'consectetur', 'id', 'sunt', 'aliquip', 'est'],
    friends: [
      {
        id: 0,
        name: 'Sarah Clayton',
      },
      {
        id: 1,
        name: 'Michael Anderson',
      },
      {
        id: 2,
        name: 'Dorothea Haley',
      },
    ],
    greeting: 'Hello, Lucia Mathis! You have 3 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '6442cf3d2b0c19bd94f23c1d',
    index: 2,
    guid: 'b66dff24-f063-45ea-b0d1-056f0ac5c484',
    isActive: false,
    balance: '$3,930.10',
    picture: 'http://placehold.it/32x32',
    age: 29,
    eyeColor: 'brown',
    name: 'Crosby Mckee',
    gender: 'male',
    company: 'OVERPLEX',
    email: 'crosbymckee@overplex.com',
    phone: '+1 (948) 451-2937',
    address: '321 Highlawn Avenue, Goochland, New York, 4493',
    about:
      'Esse pariatur id nulla ea magna qui. Proident qui excepteur incididunt adipisicing est et veniam. Minim esse eu Lorem incididunt. Ipsum nisi veniam ex ea veniam id minim id.\r\n',
    registered: '2021-01-13T03:10:16 -03:00',
    latitude: -55.331258,
    longitude: -64.108589,
    tags: ['incididunt', 'eiusmod', 'anim', 'anim', 'eiusmod', 'dolor', 'ex'],
    friends: [
      {
        id: 0,
        name: 'Georgette Pickett',
      },
      {
        id: 1,
        name: 'Jenna Neal',
      },
      {
        id: 2,
        name: 'Bray Conner',
      },
    ],
    greeting: 'Hello, Crosby Mckee! You have 4 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '6442cf3dfe07974901fcf01b',
    index: 3,
    guid: '8e868bfc-3917-4dbc-8690-f19ac139ce3f',
    isActive: false,
    balance: '$3,625.49',
    picture: 'http://placehold.it/32x32',
    age: 30,
    eyeColor: 'brown',
    name: 'Doyle Paul',
    gender: 'male',
    company: 'FROLIX',
    email: 'doylepaul@frolix.com',
    phone: '+1 (960) 526-2336',
    address: '743 Frank Court, Buxton, Kentucky, 3004',
    about:
      'Tempor ad minim mollit qui tempor aliqua cillum eiusmod minim minim. Velit laboris fugiat elit excepteur aliqua velit. Exercitation id laboris aliqua ea officia fugiat ipsum. Ad aute quis laborum duis culpa occaecat excepteur est ut dolore amet tempor ex. Ipsum duis adipisicing qui ex Lorem consequat magna exercitation ut ex aliquip non amet. Ut ea eiusmod nisi Lorem.\r\n',
    registered: '2020-06-10T09:36:56 -03:00',
    latitude: 85.075805,
    longitude: -6.053674,
    tags: ['id', 'ex', 'eu', 'excepteur', 'incididunt', 'mollit', 'qui'],
    friends: [
      {
        id: 0,
        name: 'Marquez Clemons',
      },
      {
        id: 1,
        name: 'Massey Gross',
      },
      {
        id: 2,
        name: 'Moon Lloyd',
      },
    ],
    greeting: 'Hello, Doyle Paul! You have 5 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '6442cf3d91dcef7d741bd330',
    index: 4,
    guid: '77b134f8-7b99-4ad5-ba52-f1731b88d1bb',
    isActive: false,
    balance: '$1,435.14',
    picture: 'http://placehold.it/32x32',
    age: 34,
    eyeColor: 'brown',
    name: 'Silva Norton',
    gender: 'male',
    company: 'SOFTMICRO',
    email: 'silvanorton@softmicro.com',
    phone: '+1 (919) 419-2503',
    address: '480 Clinton Avenue, Guthrie, Kansas, 6609',
    about:
      'Culpa anim consectetur esse veniam ullamco voluptate laborum nulla. Duis labore proident consectetur eiusmod eiusmod voluptate aliqua proident nisi ad. Laboris aliquip Lorem incididunt esse. Cillum voluptate pariatur nisi est consequat culpa. Lorem pariatur veniam sunt in nulla cupidatat do cillum dolor pariatur ullamco exercitation culpa. Elit cillum fugiat aute esse ipsum incididunt dolore pariatur ex.\r\n',
    registered: '2022-03-01T06:23:25 -03:00',
    latitude: -65.228606,
    longitude: -103.010304,
    tags: ['aliquip', 'nulla', 'eu', 'consectetur', 'duis', 'non', 'laboris'],
    friends: [
      {
        id: 0,
        name: 'Emerson Knapp',
      },
      {
        id: 1,
        name: 'Hardin Walker',
      },
      {
        id: 2,
        name: 'Angelica Sykes',
      },
    ],
    greeting: 'Hello, Silva Norton! You have 5 unread messages.',
    favoriteFruit: 'banana',
  },
];
